// Build 5 .docx files for week-2 presentation kit.
// Run: NODE_PATH=$(npm root -g) node scripts/build-presentation/build_docx.js
const fs = require('fs');
const path = require('path');
const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, LevelFormat, PageBreak,
  BorderStyle, WidthType, ShadingType, ExternalHyperlink,
} = require('docx');

const OUT = '/Users/bobwang/Documents/Flight Ticket Manager/docs/presentation/week-2';

const FONT = 'Arial';
const styles = {
  default: { document: { run: { font: FONT, size: 22 } } },
  paragraphStyles: [
    { id: 'Heading1', name: 'Heading 1', basedOn: 'Normal', next: 'Normal', quickFormat: true,
      run: { size: 36, bold: true, font: FONT, color: '1E2761' },
      paragraph: { spacing: { before: 320, after: 160 }, outlineLevel: 0 } },
    { id: 'Heading2', name: 'Heading 2', basedOn: 'Normal', next: 'Normal', quickFormat: true,
      run: { size: 28, bold: true, font: FONT, color: '1E2761' },
      paragraph: { spacing: { before: 240, after: 120 }, outlineLevel: 1 } },
    { id: 'Heading3', name: 'Heading 3', basedOn: 'Normal', next: 'Normal', quickFormat: true,
      run: { size: 24, bold: true, font: FONT, color: '36454F' },
      paragraph: { spacing: { before: 180, after: 80 }, outlineLevel: 2 } },
  ],
};

const numbering = {
  config: [
    { reference: 'bullets',
      levels: [
        { level: 0, format: LevelFormat.BULLET, text: '•', alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
        { level: 1, format: LevelFormat.BULLET, text: '◦', alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 1440, hanging: 360 } } } },
      ] },
    { reference: 'numbers',
      levels: [
        { level: 0, format: LevelFormat.DECIMAL, text: '%1.', alignment: AlignmentType.LEFT,
          style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
      ] },
  ],
};

const sectionDefaults = {
  properties: {
    page: {
      size: { width: 12240, height: 15840 },
      margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
    },
  },
};

const p = (text, opts = {}) => new Paragraph({ children: [new TextRun({ text, ...opts })] });
const h1 = (text) => new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun(text)] });
const h2 = (text) => new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun(text)] });
const h3 = (text) => new Paragraph({ heading: HeadingLevel.HEADING_3, children: [new TextRun(text)] });
const bullet = (text, level = 0) => new Paragraph({
  numbering: { reference: 'bullets', level }, children: [new TextRun(text)],
});
const numbered = (text) => new Paragraph({
  numbering: { reference: 'numbers', level: 0 }, children: [new TextRun(text)],
});
const blank = () => p('');
const code = (text) => new Paragraph({
  shading: { fill: 'F2F2F2', type: ShadingType.CLEAR },
  children: [new TextRun({ text, font: 'Consolas', size: 20 })],
});

function makeTable(cols, rows) {
  const totalWidth = cols.reduce((a, b) => a + b, 0);
  const border = { style: BorderStyle.SINGLE, size: 1, color: 'CCCCCC' };
  const borders = { top: border, bottom: border, left: border, right: border };
  return new Table({
    width: { size: totalWidth, type: WidthType.DXA },
    columnWidths: cols,
    rows: rows.map((row, rowIdx) => new TableRow({
      children: row.map((cellText, cellIdx) => new TableCell({
        borders,
        width: { size: cols[cellIdx], type: WidthType.DXA },
        shading: rowIdx === 0
          ? { fill: '1E2761', type: ShadingType.CLEAR }
          : { fill: rowIdx % 2 === 0 ? 'F8F9FA' : 'FFFFFF', type: ShadingType.CLEAR },
        margins: { top: 80, bottom: 80, left: 120, right: 120 },
        children: [new Paragraph({
          children: [new TextRun({
            text: String(cellText),
            bold: rowIdx === 0,
            color: rowIdx === 0 ? 'FFFFFF' : '212121',
            size: 22,
          })],
        })],
      })),
    })),
  });
}

function buildIndex() {
  return new Document({
    styles, numbering,
    sections: [{
      ...sectionDefaults,
      children: [
        h1('Week 2 演示 + 测试包'),
        p('2026-04-29 内部演示 + 公司测试 1-2 周用的全部材料。', { italics: true, color: '666666' }),
        blank(),
        h2('文档清单'),
        makeTable([2160, 2880, 4320], [
          ['文档', '给谁', '做什么用'],
          ['TEAM_ACCOUNTS.docx', '全员，先看这个', 'URL + 5 个测试账号 + 6 张 demo 订单说明'],
          ['TEST_PLAN.docx', '测试人员', 'P0/P1/P2 场景 + 验收标准（含新功能）'],
          ['DEMO_SCRIPT.docx', 'Bob 自己', '30-45 分钟分三段（客户/代理/管理员）演示流程'],
          ['FEEDBACK.docx', '全员填问题', '问题模板 + 严重度分级 + 已知问题清单'],
          ['COSTS.xlsx', '决策层 / 全员', '已花 ~$5,000 + 投产后 3 阶段月成本（4 个 Tab）'],
          ['DECK.pptx', '今天演示用', '今天 30-45 分钟的幻灯片'],
        ]),
        blank(),
        h2('Staging 环境快速链接'),
        bullet('前台（客户/代理）：http://47.83.249.163/'),
        bullet('后台（管理员）：http://47.83.249.163:8080/'),
        bullet('API 健康检查：http://47.83.249.163/api/healthz'),
        blank(),
        h3('测试账号速查'),
        p('密码统一：Password123!', { bold: true }),
        makeTable([2880, 2160, 4320], [
          ['邮箱', '角色', '入口'],
          ['admin@ftm.local', '管理员', '后台 :8080'],
          ['agent1@ftm.local', '一级代理', '前台 :80'],
          ['agent2@ftm.local', '二级代理', '前台 :80'],
          ['agent3@ftm.local', '三级代理', '前台 :80'],
          ['customer@ftm.local', '客户', '前台 :80'],
        ]),
        blank(),
        p('完整说明见 TEAM_ACCOUNTS.docx。', { italics: true }),
        blank(),
        h2('本周新功能要点'),
        numbered('「我的分成」前台页（agent 用）— 按层级看自己 + 下级的结算单 + 佣金明细'),
        numbered('批量改订单状态（admin 用）— 表头全选 + 工具条选目标状态 + 强制模式开关'),
        numbered('审计日志中文化（admin 用）— action 代码 + JSON 都翻译成人类可读，含彩色 diff'),
        blank(),
        h2('给团队群发的话'),
        code('今天演示 staging 环境：'),
        code('- 前台 http://47.83.249.163/'),
        code('- 后台 http://47.83.249.163:8080/'),
        code(''),
        code('文档（GitHub feat/m2-agent-hierarchy-flights 分支 docs/presentation/week-2/）：'),
        code('- TEAM_ACCOUNTS.docx — 账号 + 流程'),
        code('- TEST_PLAN.docx     — 怎么测'),
        code('- FEEDBACK.docx      — 报问题模板'),
        code('- COSTS.xlsx         — 成本估算'),
        code(''),
        code('1-2 周内有问题往 FEEDBACK 加；紧急的直接微信我。'),
      ],
    }],
  });
}

function buildTeamAccounts() {
  return new Document({
    styles, numbering,
    sections: [{
      ...sectionDefaults,
      children: [
        h1('测试团队账号 · Staging 环境'),
        p('仅 staging 测试用，请勿在生产环境复用同样密码。', { italics: true, color: '666666' }),
        blank(),
        h2('访问入口'),
        makeTable([2160, 3600, 3600], [
          ['入口', 'URL', '说明'],
          ['客户/代理前台', 'http://47.83.249.163/', '客户下单、代理看团队/分成'],
          ['后台管理', 'http://47.83.249.163:8080/', '管理员/运营用'],
          ['后端 API（健康检查）', 'http://47.83.249.163/api/healthz', '仅排障'],
        ]),
        blank(),
        p('当前是 IP 直连，未上 HTTPS。后续切到正式域名 + Cloudflare 才会有 HTTPS。', { italics: true, color: '999999' }),
        p('测试期间不要在测试账号里填真实身份证 / 真实银行卡。', { italics: true, color: '999999' }),
        blank(),
        h2('测试账号一览'),
        p('所有账号密码统一是：Password123!（注意首字母大写、末尾感叹号）', { bold: true, color: 'B85042' }),
        blank(),
        makeTable([1440, 2400, 1800, 3720], [
          ['角色', '邮箱', '在哪登录', '能看到 / 能做什么'],
          ['管理员', 'admin@ftm.local', '后台 :8080', '全部权限：订单批量改状态、审计日志、定价、结算单、代理管理'],
          ['一级代理', 'agent1@ftm.local', '前台 :80', '自己 + 二/三级下级；自己 + 下级的分成'],
          ['二级代理', 'agent2@ftm.local', '前台 :80', '自己 + 三级下级；自己 + 下级的分成'],
          ['三级代理', 'agent3@ftm.local', '前台 :80', '仅自己；只能看自己的分成'],
          ['客户', 'customer@ftm.local', '前台 :80', '我的订单、AI 助手下单'],
        ]),
        blank(),
        h3('注意事项'),
        bullet('客户不能在前台自助注册（已禁用）。新客户由代理在后台开通账号。'),
        bullet('代理之间是层级关系：一级看得到自己 + 二级 + 三级；二级看不到一级。'),
        bullet('后台 :8080 只允许 ADMIN/STAFF 登录，代理或客户登入会被拒。'),
        blank(),
        h2('演示数据'),
        p('种子已写入 6 张演示订单（订单号 DEMO-001 ~ DEMO-006），覆盖各种状态：'),
        blank(),
        makeTable([1800, 2160, 5400], [
          ['订单号', '状态', '用途'],
          ['DEMO-001', '已支付', '测出票 / 进入处理'],
          ['DEMO-002', '已出票', '测完成 / 改期 / 退款流程'],
          ['DEMO-003', '已完成', '历史订单查询'],
          ['DEMO-004', '退款申请中', '测审批同意 / 驳回'],
          ['DEMO-005', '已取消', '终态展示'],
          ['DEMO-006', '待支付', '测取消 / 标记已支付'],
        ]),
        blank(),
        p('所有演示订单都归 customer@ftm.local。代理登入看不到（不是自己的客户）。', { italics: true }),
        p('想测代理视角的订单，请用代理账号在前台 AI 助手 / 航班搜索手动下一单。', { italics: true }),
        blank(),
        h2('忘了密码 / 账号锁了怎么办'),
        p('直接告诉 Bob 重置。staging 环境数据可以随时 reseed，不用慎重。'),
        blank(),
        h2('i18n 切换'),
        p('页面右上角下拉框可以切换 中文 / English / Tiếng Việt。'),
        p('切换后会保存到浏览器 localStorage，下次访问自动用上次的语言。'),
      ],
    }],
  });
}

function buildTestPlan() {
  return new Document({
    styles, numbering,
    sections: [{
      ...sectionDefaults,
      children: [
        h1('测试计划 · 世途旅行 Citur Travel'),
        p('测试目标：验证 staging 上的核心业务流程能跑通，并发现影响下周公测的阻断/严重问题。'),
        p('测试周期：2026-04-29 起，1–2 周。'),
        p('反馈方式：见 FEEDBACK.docx。账号速查：见 TEAM_ACCOUNTS.docx。', { italics: true }),
        blank(),
        h2('1. 测试范围'),
        makeTable([3600, 2160, 3600], [
          ['模块', '状态', '测试优先级'],
          ['客户下单（机票/酒店/接送/签证/套餐）', '可用', 'P0'],
          ['AI 助手对话下单', '可用', 'P0'],
          ['购物车 + 结账 + 乘客信息', '可用', 'P0'],
          ['我的订单 + 取消 + 退款申请', '可用', 'P0'],
          ['代理 - 我的团队（创建下级）', '可用', 'P1'],
          ['代理 - 我的分成（新）', '新功能', 'P0 重点测'],
          ['后台 - 订单管理 + 批量改状态（新）', '可用', 'P0 重点测'],
          ['后台 - 审计日志中文化（新）', '新功能', 'P1'],
          ['后台 - 定价 / 日期等级', '可用', 'P2'],
          ['后台 - 代理 / 结算单', '可用', 'P1'],
          ['i18n - 中/英/越 切换', '可用', 'P2'],
          ['移动端预览（>= iPhone SE 宽度）', '可用', 'P1'],
        ]),
        blank(),
        h2('2. P0 测试场景（必须跑通）'),
        h3('2.1 客户从搜机票到付款全链路'),
        p('账号：customer@ftm.local / Password123!', { bold: true }),
        numbered('打开 http://47.83.249.163/'),
        numbered('首页搜索：澳门(MFM) → 岘港(DAD)，选未来 7 天某天'),
        numbered('点击搜索结果中的"立即预订"'),
        numbered('加入购物车，进入结账'),
        numbered('填写联系信息 + 乘客信息（人数 = 票数）'),
        numbered('点"立即支付"，看是否进入沙盒支付页 → 模拟成功'),
        numbered('进入"我的订单"，看是否出现刚下的订单，状态是"已支付"'),
        blank(),
        p('验收标准：', { bold: true }),
        bullet('每一步页面无报错'),
        bullet('下单后订单立即出现在"我的订单"'),
        bullet('切换中/英/越，所有按钮和标题都翻译过来'),
        blank(),
        h3('2.2 AI 助手下单'),
        p('账号：customer@ftm.local', { bold: true }),
        numbered('进入首页，右下角点 AI 助手浮窗'),
        numbered('输入：「明天 2 个人去岘港，要往返票」'),
        numbered('看 AI 是否给出航班建议 + 价格'),
        numbered('点"OK · 看详情" 看明细'),
        numbered('点"确认下单" → 应跳到结账页'),
        blank(),
        p('验收标准：', { bold: true }),
        bullet('AI 推理时间 < 5 秒（不算等待）'),
        bullet('推荐结果与航班搜索一致'),
        bullet('加购后购物车数量 +1'),
        blank(),
        h3('2.3 代理看自己的分成（新功能）'),
        p('账号：agent1@ftm.local / Password123!', { bold: true }),
        numbered('登入前台（http://47.83.249.163/）'),
        numbered('顶部 nav 应该看到「我的团队」+「我的分成」两个链接'),
        numbered('点「我的分成」'),
        numbered('应该看到 4 张 KPI 卡 + 过滤区 + 结算单表格'),
        numbered('切换"范围"过滤（自己 / 仅下级 / 自己+下级），数据应该跟着变'),
        numbered('点表格里某条结算单 → 右侧抽屉打开看明细'),
        blank(),
        p('验收标准：', { bold: true }),
        bullet('一级代理能看到自己 + 二级 + 三级的结算单'),
        bullet('二级登入只能看到自己 + 三级'),
        bullet('三级登入只能看到自己'),
        bullet('"我自己"那一行有蓝色徽章标识'),
        bullet('金额数字显示成「¥1,234.56」格式'),
        blank(),
        h3('2.4 后台批量改订单状态（新功能）'),
        p('账号：admin@ftm.local（在后台 :8080 登）', { bold: true }),
        numbered('进「订单管理」'),
        numbered('列表上每行有勾选框，表头有全选框'),
        numbered('勾选 2-3 单 → 顶部出现批量操作工具条'),
        numbered('选目标状态（比如"已支付"），点"应用"'),
        numbered('看是否所有勾选订单状态都改了'),
        blank(),
        p('验收标准：', { bold: true }),
        bullet('全选 + 反选 + 取消选都正确'),
        bullet('默认开"强制模式"，可绕过状态机校验'),
        bullet('关掉强制模式时，不允许的状态流转会失败并显示错误明细'),
        bullet('单条订单"操作"列也有「改状态…」下拉，可以快速改单条'),
        blank(),
        h3('2.5 后台审计日志可读化（新功能）'),
        p('账号：admin@ftm.local', { bold: true }),
        numbered('进「审计日志」'),
        numbered('应该看到一堆人类可读的中文动作（不是 BATCH_FORCE_ORDER_STATUS 这种代码）'),
        numbered('"变更摘要"列应该是「目标状态: 待支付 → 已支付」这类一句话'),
        numbered('点任意一条 → 右侧抽屉打开'),
        numbered('抽屉里"变更"区是分行的彩色 diff（−红 / +绿）'),
        numbered('抽屉底部有"查看原始 JSON"折叠区，可以看后台原始数据'),
        blank(),
        p('验收标准：', { bold: true }),
        bullet('表格里看不到全大写动作代码（小灰字除外）'),
        bullet('金额自动加 ¥'),
        bullet('OrderStatus 等枚举显示中文'),
        bullet('原始 JSON 折叠区能展开'),
        blank(),
        h2('3. P1 测试场景'),
        h3('3.1 代理创建下级'),
        bullet('用 agent1 登入 → 进「我的团队」'),
        bullet('试着创建一个新二级代理：填邮箱 + 手机 + 名字'),
        bullet('创建后告诉 Bob 看新代理是否能登入'),
        blank(),
        h3('3.2 取消订单 → 退款流程'),
        bullet('用 customer 下一个新单（不要用 DEMO-* 那些）'),
        bullet('走完结账，状态变"已支付"'),
        bullet('进"我的订单"，点取消 → 看退款报价 → 确认'),
        bullet('订单状态变"退款申请中"'),
        bullet('用 admin 进后台，找到这单 → 同意退款'),
        bullet('客户端订单状态变"已退款"'),
        blank(),
        h2('4. P2 测试场景（如果有时间）'),
        bullet('移动端 iPhone 宽度（375px）下所有页面布局正确'),
        bullet('切到英文后所有文字都翻译（不留中文残留）'),
        bullet('切到越南语同上'),
        bullet('后台批量改状态超过 50 条会不会卡'),
        bullet('退款部分批准 / 整单驳回流程'),
        bullet('AI 助手聊天历史持久化（刷新页面后还在）'),
        blank(),
        h2('5. 已知不测的部分'),
        bullet('真实支付：当前是沙盒模式，不会扣钱'),
        bullet('真实出票：后台点"出票完成"只是改状态，不会调真航司接口'),
        bullet('小程序：还没部署，本次测试不涉及'),
        bullet('HTTPS：IP 直连还没证书，浏览器会显示"不安全"，正常'),
        bullet('OCR / 护照识别：客户端有功能但识别率约 60-75%，不必特意测'),
        blank(),
        h2('6. 严重程度划分'),
        makeTable([1440, 2160, 5760], [
          ['P 级', '含义', '例子'],
          ['P0', '阻断公测', '登入失败 / 下单按钮没反应 / 后台白屏'],
          ['P1', '严重缺陷', '价格算错 / 状态流转出错 / 中文显示成乱码'],
          ['P2', '一般缺陷', 'UI 错位 / 翻译不全 / loading 转圈不消失'],
          ['P3', '改进建议', '文案不顺 / 按钮位置可优化 / 增加快捷功能'],
        ]),
        blank(),
        p('任何卡住的地方，截图 + URL + 步骤，丢给 Bob。', { italics: true, bold: true }),
      ],
    }],
  });
}

function buildDemoScript() {
  return new Document({
    styles, numbering,
    sections: [{
      ...sectionDefaults,
      children: [
        h1('今天演示脚本 · 30-45 分钟'),
        p('给 Bob 自己用：按这个顺序演示，避免临场卡壳。', { italics: true, color: '666666' }),
        p('团队边看边在 FEEDBACK.docx 记录想法。', { italics: true, color: '666666' }),
        blank(),
        h2('开场（2 分钟）'),
        p('"我们做的是一个旅游 SaaS，主营澳门 ↔ 岘港直飞航线。', { italics: true }),
        p('客户在前台下单买票/酒店/接送/签证；代理在前台管下级 + 看分成；', { italics: true }),
        p('我们运营在后台管订单 + 财务结算。', { italics: true }),
        p('今天演示 staging 环境，所有数据都是测试的，不会扣钱。"', { italics: true }),
        blank(),
        p('提前打开 4 个标签页：', { bold: true }),
        numbered('前台 http://47.83.249.163/'),
        numbered('后台 http://47.83.249.163:8080/'),
        numbered('FEEDBACK.docx（让团队边看边记）'),
        numbered('TEAM_ACCOUNTS.docx（账号速查）'),
        blank(),
        h2('第一段 · 客户视角（10 分钟）'),
        h3('Step 1 · 首页 + 搜机票（不登录）'),
        bullet('打开 http://47.83.249.163/'),
        bullet('介绍：「澳门直飞岘港，自营航班，每天 1 班」'),
        bullet('顶部 nav 五大块：机票 / 酒店 / 接送 / 签证 / 套餐'),
        bullet('搜索：MFM → DAD，下周四'),
        bullet('点结果中价格最高的那条 → 商务舱卡片'),
        bullet('重点演示：动态价格 + 限时优惠标识'),
        bullet('加购物车 → 进结账'),
        blank(),
        h3('Step 2 · 登入 customer 完成下单'),
        bullet('退出，登入 customer@ftm.local / Password123!'),
        bullet('进结账页：填联系信息 + 乘客信息'),
        bullet('重点演示：乘客数 = 票数（少了系统会拦）'),
        bullet('点支付 → 沙盒成功'),
        bullet('进"我的订单"看新订单'),
        blank(),
        h3('Step 3 · AI 助手下单'),
        bullet('退到首页，点右下角浮窗 🤖'),
        bullet('输入：「明天 2 个人去岘港，要往返」'),
        bullet('AI 给方案 → 点"OK·看详情" → "确认下单"'),
        bullet('进结账页（AI 已经把信息填好）'),
        blank(),
        p('演示要点：「客户不会自己想去打开 5 个页面比价；AI 一句话就帮他搞定。」', { italics: true, color: '028090' }),
        blank(),
        h2('第二段 · 代理视角（10 分钟）'),
        h3('Step 4 · 一级代理看团队'),
        bullet('退出，登入 agent1@ftm.local'),
        bullet('nav 多了「我的团队」和「我的分成」（重点：刚加的）'),
        bullet('进「我的团队」'),
        bullet('看到二级 + 三级的层级结构'),
        bullet('试着新建一个二级代理（填邮箱 + 手机 + 名字）'),
        blank(),
        h3('Step 5 · 一级代理看分成（核心新功能）'),
        bullet('进「我的分成」'),
        bullet('指着 4 个 KPI 卡讲：我的应得 / 下级累计 / 待打款 / 结算单总数'),
        bullet('切换"范围"过滤 → 仅自己 / 仅下级 / 全部'),
        bullet('点开任意一行结算单 → 右侧抽屉'),
        bullet('抽屉里讲：销售额 / 应得佣金 / 分给下级 / 应付（含预付抵扣）'),
        bullet('滚到底部看「佣金明细」表（按订单 + 产品类型）'),
        blank(),
        p('演示要点：', { bold: true }),
        bullet('一级代理能看到所有下级的分成（透明）'),
        bullet('自己那行有「我自己」蓝徽章标识'),
        bullet('金额都是 ¥ 格式，不是裸数字'),
        bullet('状态机：草稿 → 待审批 → 已核准 → 已支付'),
        blank(),
        h3('Step 6 · 切到二级代理对比'),
        bullet('退出，登入 agent2@ftm.local'),
        bullet('进「我的分成」'),
        bullet('重点：只能看到自己 + 三级，看不到一级 → 这就是层级 RBAC'),
        blank(),
        h2('第三段 · 管理员视角（15 分钟）'),
        h3('Step 7 · 后台登入'),
        bullet('打开 http://47.83.249.163:8080/'),
        bullet('登入 admin@ftm.local / Password123!'),
        bullet('左侧 nav 一圈：订单 / 代理 / 客户 / 出行人 / 定价 / 结算 / 履约 / 审计'),
        blank(),
        h3('Step 8 · 订单管理 + 批量改状态（核心新功能）'),
        bullet('进「订单管理」'),
        bullet('看到 6 条 DEMO-* 订单 + 客户/代理刚下的真单'),
        p('重点演示批量：', { bold: true }),
        bullet('勾选 3 单', 1),
        bullet('顶部出现工具条：「已选 3 条 ｜ 改为 [下拉] [强制] [应用] [清除]」', 1),
        bullet('选「已支付」 → 应用', 1),
        bullet('看 3 单状态都变了', 1),
        p('重点演示行内单改：', { bold: true }),
        bullet('找一条订单，右侧"操作"列', 1),
        bullet('点「改状态…」下拉 → 选目标状态', 1),
        bullet('弹确认框 → 确认 → 状态变了', 1),
        blank(),
        p('演示要点：', { bold: true }),
        bullet('默认"强制模式"，可绕过状态机（管理员特权）'),
        bullet('关掉强制模式则按标准流转'),
        bullet('批量出错时会显示失败明细'),
        blank(),
        h3('Step 9 · 审计日志可读化（新功能）'),
        bullet('进「审计日志」'),
        bullet('对比讲：「以前这页都是 BATCH_FORCE_ORDER_STATUS 这种代码 + 一坨 JSON，没法看。现在：」'),
        bullet('表格"动作"列：emoji + 中文（小灰字保留原始代码）'),
        bullet('"变更摘要"列：「目标状态: 待支付 → 已支付」一句话'),
        bullet('点任意一行 → 抽屉'),
        bullet('抽屉"变更"区：彩色 diff（−红 +绿）'),
        bullet('底部"查看原始 JSON"折叠区可展开（给开发排障用）'),
        blank(),
        h3('Step 10 · 其他后台模块（快速过）'),
        bullet('代理：层级结构 + 预付余额管理'),
        bullet('结算：月度结算单 + 状态流转'),
        bullet('定价：日期等级 + 余位阶梯（动态价引擎）'),
        bullet('履约：自动出票任务队列'),
        blank(),
        h2('收尾（3 分钟）'),
        p('"短期目标：1-2 周内大家把 P0/P1 都跑一遍，把 FEEDBACK 填满。', { italics: true }),
        p('我每天看一次 FEEDBACK，每天改一波，每周末重 deploy。', { italics: true }),
        p('公测之前会上正式域名 + Cloudflare WAF + HTTPS。"', { italics: true }),
        blank(),
        h3('提问环节'),
        bullet('客户角度：还差什么必备功能？'),
        bullet('代理角度：分成显示是不是够清楚？要不要加导出 PDF？'),
        bullet('运营角度：批量改状态够用吗？要不要加批量退款？'),
        blank(),
        h2('演示中可能被问到的问题'),
        makeTable([3600, 5760], [
          ['问题', '怎么答'],
          ['价格能不能自动算优惠？', '可以，已有日期等级 + 余位阶梯两层动态定价'],
          ['代理佣金率能改吗？', '后台「定价」模块可以按代理+产品类型设佣金率'],
          ['客户能自己注册吗？', '不行。注册由代理后台开通（防黄牛）'],
          ['出票是真的吗？', '当前沙盒；接航司接口在 milestone 3'],
          ['数据安全吗？', '备份每日跑；后续接 Cloudflare WAF'],
          ['移动端怎么样？', '已适配，可在 nav 点「移动预览」实时看'],
          ['多语言支持哪些？', '中/英/越，右上角切换'],
          ['上线时间？', '公测 1-2 周后；正式上线视测试结果'],
        ]),
      ],
    }],
  });
}

function buildFeedback() {
  // 用 ☐ 字符模拟 checkbox（员工自己用 ✓ 或 ✗ 填）
  const cb = (text) => p(`☐  ${text}`);
  const line = (label, helper = '') => new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true }),
      new TextRun({ text: '___________________________________', color: '999999' }),
      ...(helper ? [new TextRun({ text: `   （${helper}）`, italics: true, size: 18, color: '999999' })] : []),
    ],
  });
  const blankLine = () => p('___________________________________________________________________', { color: 'CCCCCC' });

  const problemBlock = (n) => [
    h3(`问题 ${n}`),
    p('在哪个页面 / 用哪个账号遇到的？（勾一个或几个）', { bold: true }),
    cb('客户首页 / 搜机票'),
    cb('客户购物车 / 结账 / 我的订单'),
    cb('AI 助手聊天'),
    cb('代理 — 我的团队'),
    cb('代理 — 我的分成'),
    cb('管理员后台 — 订单管理'),
    cb('管理员后台 — 其他模块'),
    cb('小程序 / 手机端'),
    cb('其他（写下来）: __________________________'),
    blank(),
    p('发生了什么？（你点了什么按钮、看到什么提示、和你想的不一样在哪）', { bold: true }),
    blankLine(),
    blankLine(),
    blankLine(),
    blank(),
    p('严重程度', { bold: true }),
    cb('还好 — 能将就用，只是看着别扭'),
    cb('有点麻烦 — 要绕一下才能完成，但能完成'),
    cb('影响我工作 — 这步走不下去，做不了事'),
    blank(),
    p('如果方便，附一张截图（直接贴在下面 或 微信发给 Bob）', { italics: true, color: '666666' }),
    blank(), blank(),
  ];

  const wishBlock = (n) => [
    h3(`想要的功能 ${n}`),
    p('你希望多一个什么功能？或者哪里能改得更顺手？', { bold: true }),
    blankLine(),
    blankLine(),
    blankLine(),
    blank(),
    p('为什么需要这个？（举一个真实例子）', { bold: true }),
    blankLine(),
    blankLine(),
    blank(),
    p('你觉得有多重要？', { bold: true }),
    cb('锦上添花 — 有了挺好，没有也行'),
    cb('挺有用 — 经常会用到'),
    cb('必须有 — 不加这个我就用不起来'),
    blank(), blank(),
  ];

  return new Document({
    styles, numbering,
    sections: [{
      ...sectionDefaults,
      children: [
        h1('测试反馈表'),
        p('—— 世途旅行 Citur Travel · 内部公测 ——', { italics: true, color: '666666' }),
        blank(),

        p('请大家用 1-2 周时间随便点点、试试。', { bold: true }),
        p('遇到什么不顺手、或者觉得"如果有 XX 功能就好了"，就在这张表上写一条。'),
        p('交给 Bob：直接微信发文件 / 当面给 / 邮箱发都行。'),
        p('紧急的（页面打不开、登不上、数据不对）直接微信 Bob，不用填这张。', { italics: true, color: 'B85042' }),
        blank(),

        h2('你是谁'),
        line('名字'),
        line('日期', '比如 2026-05-13'),
        line('角色', '客户视角 / 代理 / 运营 / 老板 等'),
        line('联系方式（可不填）', '微信 / 手机 — 方便 Bob 追问'),
        blank(),

        line('你这次主要测了多久', '比如 30 分钟 / 半天'),
        p('你这次主要测了什么？（勾一个或几个）', { bold: true }),
        cb('我当客户 — 试着下单买机票 / 酒店 / 接送 / 签证'),
        cb('我当代理 — 看自己的分成、管下级'),
        cb('我当管理员 — 改订单状态、看审计日志、跑结算'),
        cb('我试了 AI 助手聊天'),
        cb('我用手机 / 小程序看了看'),
        cb('其他: __________________________'),
        blank(),

        h2('一、你遇到了什么问题？'),
        p('（最多写 3 个；写不下了用反面 / 微信补）', { italics: true, color: '666666' }),
        blank(),
        ...problemBlock(1),
        ...problemBlock(2),
        ...problemBlock(3),

        new Paragraph({ children: [new PageBreak()] }),

        h2('二、你希望增加什么功能？'),
        p('（不限于现在有的；想到什么写什么，越具体越好）', { italics: true, color: '666666' }),
        blank(),
        ...wishBlock(1),
        ...wishBlock(2),
        ...wishBlock(3),

        h2('三、总体感受'),
        p('你觉得现在这个东西，比起你现在用的方式（手动 / 别家平台 / Excel）：', { bold: true }),
        cb('好用很多 — 真用得起来'),
        cb('差不多 — 各有优劣'),
        cb('比现在差 — 不会切过来'),
        blank(),

        p('哪一块最让你眼前一亮？', { bold: true }),
        blankLine(),
        blankLine(),
        blank(),

        p('哪一块让你最想吐槽？', { bold: true }),
        blankLine(),
        blankLine(),
        blank(),

        p('如果给现在的产品打分（1 = 完全不能用，10 = 立刻上线我天天用）：', { bold: true }),
        p('1   2   3   4   5   6   7   8   9   10', { color: '999999' }),
        blank(), blank(),

        h2('几件不用反馈的事'),
        p('（这几个我们已经知道、是故意的，不用专门提）', { italics: true, color: '666666' }),
        blank(),
        bullet('浏览器顶部显示"不安全" — 正常，公测前会换正式域名 + HTTPS。'),
        bullet('点"支付成功"但银行卡没扣钱 — 正常，现在是沙盒模式，不会真扣。'),
        bullet('点"出票"没真出票 — 正常，没接航司接口，只是改个状态给你看。'),
        bullet('客户端不能自己注册账号 — 故意的，新客户由代理后台开通。'),
        bullet('护照拍照识别有时不准 — 已知问题，后续接服务端 OCR 提升。'),
        blank(),

        h2('感谢你！'),
        p('每一条反馈我们都会看，能改的当天就改。', { italics: true }),
        p('改完之后会在群里说"已修复"，你可以再确认一次。', { italics: true }),
      ],
    }],
  });
}

const targets = [
  { name: 'INDEX.docx', doc: buildIndex() },
  { name: 'TEAM_ACCOUNTS.docx', doc: buildTeamAccounts() },
  { name: 'TEST_PLAN.docx', doc: buildTestPlan() },
  { name: 'DEMO_SCRIPT.docx', doc: buildDemoScript() },
  { name: 'FEEDBACK.docx', doc: buildFeedback() },
];

(async () => {
  for (const { name, doc } of targets) {
    const buf = await Packer.toBuffer(doc);
    const out = path.join(OUT, name);
    fs.writeFileSync(out, buf);
    console.log(`Saved: ${out}  (${buf.length.toLocaleString()} bytes)`);
  }
})();
