#!/usr/bin/env bash
# 阿里云香港轻量服务器 1 键 staging 部署脚本
#
# 用法（SSH 上服务器后）：
#   curl -fsSL https://raw.githubusercontent.com/bobzhendeniubi/flight-ticket-manager/feat/m2-agent-hierarchy-flights/infra/staging/deploy.sh | bash
#
# 或者 git clone 后跑：
#   cd /opt && git clone https://github.com/bobzhendeniubi/flight-ticket-manager.git ftm
#   cd ftm && bash infra/staging/deploy.sh
#
# 脚本做的事：
#   1. 装 docker + docker compose plugin
#   2. 装 caddy（自动 HTTPS）+ ufw + fail2ban
#   3. clone 项目（如果还没 clone）
#   4. 生成 .env.prod（强随机密钥）
#   5. docker compose build + up
#   6. prisma migrate deploy + seed
#   7. 配 Caddy 反代（用户后续 vim Caddyfile 改 domain）
#   8. 启 unattended-upgrades 自动安全补丁
set -euo pipefail

# ── 颜色 ─────────────────────────────────────────────────────────
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'
log()  { echo -e "${GREEN}[deploy] $*${NC}"; }
warn() { echo -e "${YELLOW}[deploy] $*${NC}"; }
fail() { echo -e "${RED}[deploy] $*${NC}"; exit 1; }

# ── 0. 必须 root ─────────────────────────────────────────────────
[ "$EUID" -eq 0 ] || fail "请用 root 跑（sudo bash deploy.sh）"

REPO_DIR="${REPO_DIR:-/opt/ftm}"
REPO_URL="${REPO_URL:-https://github.com/bobzhendeniubi/flight-ticket-manager.git}"
REPO_BRANCH="${REPO_BRANCH:-feat/m2-agent-hierarchy-flights}"

# ── 1. 系统更新 + 装包 ───────────────────────────────────────────
log "1/8 系统更新 + 装基础工具"
if command -v dnf &>/dev/null; then
  dnf update -y -q || true
  dnf install -y -q git curl jq openssl ufw fail2ban policycoreutils-python-utils || \
    dnf install -y -q git curl jq openssl
else
  apt-get update -qq
  apt-get install -y -qq git curl jq openssl ufw fail2ban
fi

# ── 2. 装 Docker ─────────────────────────────────────────────────
log "2/8 装 Docker"
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh
fi
systemctl enable --now docker
docker --version

# ── 3. 装 Caddy（自动 HTTPS + Let's Encrypt）─────────────────────
log "3/8 装 Caddy"
if ! command -v caddy &>/dev/null; then
  if command -v dnf &>/dev/null; then
    dnf install -y -q 'dnf-command(copr)' || true
    dnf copr enable -y @caddy/caddy || true
    dnf install -y -q caddy || warn "Caddy 装失败（COPR 不可用）— 后续手动装"
  else
    apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/caddy-stable-archive-keyring.gpg] https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main" >/etc/apt/sources.list.d/caddy-stable.list
    apt-get update -qq && apt-get install -y -qq caddy
  fi
fi
systemctl enable caddy 2>/dev/null || true

# ── 4. 防火墙：只开 22/80/443 ────────────────────────────────────
log "4/8 配 ufw 防火墙"
if command -v ufw &>/dev/null; then
  ufw --force reset
  ufw default deny incoming
  ufw default allow outgoing
  ufw allow 22/tcp comment 'ssh'
  ufw allow 80/tcp comment 'http'
  ufw allow 443/tcp comment 'https'
  ufw --force enable
else
  warn "ufw 未装（阿里云轻量已经在控制台层面有防火墙，可跳过）"
fi

# ── 5. fail2ban 防 SSH 暴力破解 ──────────────────────────────────
log "5/8 配 fail2ban"
if command -v fail2ban-client &>/dev/null; then
  cat >/etc/fail2ban/jail.local <<'EOF'
[DEFAULT]
bantime  = 3600
findtime = 600
maxretry = 3

[sshd]
enabled = true
port    = 22
EOF
  systemctl enable --now fail2ban
fi

# ── 6. clone 项目 ────────────────────────────────────────────────
log "6/8 clone 项目"
if [ -d "$REPO_DIR/.git" ]; then
  log "已存在 $REPO_DIR，git pull 更新"
  cd "$REPO_DIR" && git fetch && git checkout "$REPO_BRANCH" && git pull
else
  mkdir -p "$REPO_DIR"
  git clone --branch "$REPO_BRANCH" "$REPO_URL" "$REPO_DIR"
  cd "$REPO_DIR"
fi

# ── 7. 生成 .env.prod ────────────────────────────────────────────
log "7/8 生成 .env.prod"
ENV_FILE="$REPO_DIR/.env.prod"
if [ -f "$ENV_FILE" ]; then
  warn ".env.prod 已存在，不覆盖。要重新生成先 mv .env.prod .env.prod.bak"
else
  rand48() { openssl rand -base64 48 | tr -d '\n='; }
  rand24() { openssl rand -base64 24 | tr -d '\n=/+' | head -c 24; }
  cat >"$ENV_FILE" <<EOF
# Auto-generated by infra/staging/deploy.sh on $(date -Iseconds)
POSTGRES_PASSWORD=$(rand24)
JWT_ACCESS_SECRET=$(rand48)
JWT_REFRESH_SECRET=$(rand48)
JWT_ACCESS_TTL=900
JWT_REFRESH_TTL=604800
CORS_ORIGINS=https://sales.example.com,https://admin.example.com
APP_PUBLIC_URL=https://api.example.com
VITE_API_BASE=/api
LOG_LEVEL=info
PAYMENT_MODE=sandbox
SANDBOX_WEBHOOK_SECRET=$(rand24)
ENABLE_AUTO_FULFILLMENT=true
NODE_ENV=production
EOF
  chmod 600 "$ENV_FILE"
  log "已生成 $ENV_FILE（chmod 600）"
  warn "⚠️  改完域名再 docker compose restart：vim $ENV_FILE  → CORS_ORIGINS / APP_PUBLIC_URL"
fi

# ── 8. docker compose up ─────────────────────────────────────────
log "8/8 docker compose build + up"
cd "$REPO_DIR"
docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --build

log "等数据库 ready..."
for i in {1..30}; do
  if docker exec ftm-postgres-prod pg_isready -U ftm -d ftm &>/dev/null; then
    log "postgres ready，等 5 秒让 backend 完成 migrate..."
    sleep 5
    break
  fi
  sleep 2
done

# ── 9. prisma seed（首次）────────────────────────────────────────
if docker ps --format '{{.Names}}' | grep -q ftm-backend-prod; then
  log "跑 prisma db seed（demo 数据）"
  docker exec ftm-backend-prod npx prisma db seed || warn "seed 失败或已 seed 过"
else
  warn "backend 容器未就绪，跳过 seed。手动跑：docker exec -it ftm-backend-prod npx prisma db seed"
fi

# ── 10. unattended-upgrades 自动安全补丁 ─────────────────────────
log "配自动安全补丁"
if command -v dnf &>/dev/null; then
  dnf install -y -q dnf-automatic 2>/dev/null || true
  if [ -f /etc/dnf/automatic.conf ]; then
    sed -i 's/^apply_updates = no/apply_updates = yes/' /etc/dnf/automatic.conf || true
    systemctl enable --now dnf-automatic.timer 2>/dev/null || true
  fi
else
  apt-get install -y -qq unattended-upgrades
  echo 'APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";' >/etc/apt/apt.conf.d/20auto-upgrades
fi

# ── 完成 ─────────────────────────────────────────────────────────
PUBIP=$(curl -fsS ipv4.icanhazip.com 2>/dev/null || hostname -I | awk '{print $1}')
echo ""
log "═══════════════════════════════════════════════"
log "✅ 部署完成"
log "═══════════════════════════════════════════════"
echo ""
echo "本机公网 IP：$PUBIP"
echo ""
echo "下一步："
echo ""
echo "1. 在域名注册商加 3 条 A 记录指向 $PUBIP："
echo "     sales.<你的域名>  → $PUBIP"
echo "     admin.<你的域名>  → $PUBIP"
echo "     api.<你的域名>    → $PUBIP"
echo ""
echo "2. 配 Caddy 反代（自动 HTTPS）："
echo "     cp $REPO_DIR/infra/staging/Caddyfile.example /etc/caddy/Caddyfile"
echo "     vim /etc/caddy/Caddyfile     # 把 your-domain.com 换成真域名"
echo "     systemctl restart caddy"
echo ""
echo "3. 改 .env.prod 里的 CORS_ORIGINS / APP_PUBLIC_URL 用真域名："
echo "     vim $REPO_DIR/.env.prod"
echo "     cd $REPO_DIR && docker compose -f docker-compose.prod.yml --env-file .env.prod up -d --force-recreate backend worker"
echo ""
echo "4. 健康检查（暂时 IP 直连）："
echo "     curl http://$PUBIP/api/readyz"
echo ""
echo "默认 demo 账号：admin@ftm.local / Password123!"
echo ""
